// Code generated by MockGen. DO NOT EDIT.
// Source: webhook.go

// Package webhook is a generated GoMock package.
package webhook

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Mockmetricser is a mock of metricser interface
type Mockmetricser struct {
	ctrl     *gomock.Controller
	recorder *MockmetricserMockRecorder
}

// MockmetricserMockRecorder is the mock recorder for Mockmetricser
type MockmetricserMockRecorder struct {
	mock *Mockmetricser
}

// NewMockmetricser creates a new mock instance
func NewMockmetricser(ctrl *gomock.Controller) *Mockmetricser {
	mock := &Mockmetricser{ctrl: ctrl}
	mock.recorder = &MockmetricserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockmetricser) EXPECT() *MockmetricserMockRecorder {
	return m.recorder
}

// IncomeTaskInc mocks base method
func (m *Mockmetricser) IncomeTaskInc(rule, alert, executor string) {
	m.ctrl.Call(m, "IncomeTaskInc", rule, alert, executor)
}

// IncomeTaskInc indicates an expected call of IncomeTaskInc
func (mr *MockmetricserMockRecorder) IncomeTaskInc(rule, alert, executor interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncomeTaskInc", reflect.TypeOf((*Mockmetricser)(nil).IncomeTaskInc), rule, alert, executor)
}
